print('Hello from master')
print('Hello from master2')
print('Hello from Adilet')
print('Hello from branch Adi')
print('Hello from branch Adi2')
print('Hello from branch Adi3')
print('Koala best animal')