# Generated by Django 5.1.1 on 2024-09-10 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Cлаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=20, verbose_name='Размер')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Cлаг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='product.category')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Subsubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название подподкатегории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Cлаг')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategory', to='product.subcategory')),
            ],
            options={
                'verbose_name': 'Подподкатегория',
                'verbose_name_plural': 'Подподкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('articul', models.PositiveIntegerField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('compound', models.CharField(blank=True, max_length=200, null=True, verbose_name='Состав')),
                ('season', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сезон')),
                ('shoe_sole_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал подошвы обуви')),
                ('shoe_lining_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал подкладки обуви')),
                ('insole_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал стельки')),
                ('sole_height', models.CharField(blank=True, max_length=200, null=True, verbose_name='Высота подошвы')),
                ('country_of_origin', models.CharField(blank=True, max_length=200, null=True, verbose_name='Страна производства')),
                ('equipment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Комплектация')),
                ('clasp_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вид застежки')),
                ('model_features', models.CharField(blank=True, max_length=200, null=True, verbose_name='Особенности модели')),
                ('product_model', models.CharField(blank=True, max_length=200, null=True, verbose_name='Модель')),
                ('warranty_period', models.CharField(blank=True, max_length=200, null=True, verbose_name='Гарантийный срок')),
                ('nutrition', models.CharField(blank=True, max_length=200, null=True, verbose_name='Питание')),
                ('wireless_interfaces', models.CharField(blank=True, max_length=200, null=True, verbose_name='Беспроводные интерфейсы')),
                ('effect', models.CharField(blank=True, max_length=200, null=True, verbose_name='Эффект средства')),
                ('item_width', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ширина предмета')),
                ('item_height', models.CharField(blank=True, max_length=200, null=True, verbose_name='Высота предмета')),
                ('quantity_package', models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество в упаковке')),
                ('housing_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал корпуса')),
                ('handle_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип ручки')),
                ('number_branches', models.CharField(blank=True, max_length=200, null=True, verbose_name='Количество отделений')),
                ('backpack_size', models.CharField(blank=True, max_length=200, null=True, verbose_name='Размер рюкзака')),
                ('lining_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал прокладки')),
                ('backpack_capacity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вместимость рюкзака')),
                ('pockets', models.CharField(blank=True, max_length=200, null=True, verbose_name='Карманы')),
                ('product_material', models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал изделия')),
                ('max_load', models.CharField(blank=True, max_length=200, null=True, verbose_name='Максимальная нагрузка')),
                ('mounting_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип крепления')),
                ('package_length', models.CharField(blank=True, max_length=200, null=True, verbose_name='Длина упаковки')),
                ('package_height', models.CharField(blank=True, max_length=200, null=True, verbose_name='Высота упаковки')),
                ('package_width', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ширина упаковки')),
                ('battery_capacity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ёмкость аккумулятора')),
                ('battery_life', models.CharField(blank=True, max_length=200, null=True, verbose_name='Время работы от аккумулятора')),
                ('screen_size', models.CharField(blank=True, max_length=200, null=True, verbose_name='Размер экрана')),
                ('resolution', models.CharField(blank=True, max_length=200, null=True, verbose_name='Разрешение экрана')),
                ('connectivity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Подключение')),
                ('storage_capacity', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ёмкость памяти')),
                ('operating_system', models.CharField(blank=True, max_length=200, null=True, verbose_name='Операционная система')),
                ('processor_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='Тип процессора')),
                ('weight', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вес')),
                ('color_variants', models.CharField(blank=True, max_length=200, null=True, verbose_name='Варианты цвета')),
                ('size_variants', models.CharField(blank=True, max_length=200, null=True, verbose_name='Варианты размера')),
                ('environmental_rating', models.CharField(blank=True, max_length=200, null=True, verbose_name='Экологический рейтинг')),
                ('energy_rating', models.CharField(blank=True, max_length=200, null=True, verbose_name='Энергетический рейтинг')),
                ('compatibility', models.CharField(blank=True, max_length=200, null=True, verbose_name='Совместимость')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Срок годности')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска')),
                ('usage_area', models.CharField(blank=True, max_length=200, null=True, verbose_name='Область применения')),
                ('safety_warnings', models.TextField(blank=True, null=True, verbose_name='Предупреждения о безопасности')),
                ('price_range', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ценовой диапазон')),
                ('model_year', models.CharField(blank=True, max_length=200, null=True, verbose_name='Год модели')),
                ('seasonal_offer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сезонное предложение')),
                ('production_batch', models.CharField(blank=True, max_length=200, null=True, verbose_name='Партийный номер')),
                ('import_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Статус импорта')),
                ('shelf_life', models.CharField(blank=True, max_length=200, null=True, verbose_name='Срок хранения')),
                ('certification_marks', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сертификационные знаки')),
                ('eco_friendly', models.CharField(blank=True, max_length=200, null=True, verbose_name='Экологически чистый')),
                ('manufacturer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя производителя')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('sizes', models.ManyToManyField(related_name='products', to='product.size')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subcategory')),
                ('subsubcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.subsubcategory')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
