# Generated by Django 5.1 on 2024-09-21 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название бренда')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Cлаг')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название машины')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет машины')),
                ('engine_type', models.CharField(max_length=100, verbose_name='Тип двигателя')),
                ('drivers_location', models.CharField(max_length=100, verbose_name='Расположение водительского кресла')),
                ('drive_type', models.CharField(max_length=100, verbose_name='Тип привода')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Объем')),
                ('year_manufacture', models.CharField(max_length=100, verbose_name='Год выпуска')),
                ('body', models.CharField(max_length=100, verbose_name='Кузов')),
                ('Country_origin', models.CharField(max_length=200, verbose_name='Страна производства')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='product.brand')),
            ],
        ),
    ]
